name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main    # Trigger pipeline on push to main branch

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t myflaskapp:latest .

      - name: Test Docker Container
        run: |
            docker run --name test-container -d myflaskapp:latest
            docker logs test-container   # Check that app started correctly
            docker stop test-container
            docker rm test-container


  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build    # Runs only after build job completes successfully
    steps:
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                docker stop myflaskapp || true
                docker rm myflaskapp || true
                docker run -d -p 5000:5000 myflaskapp:latest

